# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib sassyRS, .registration = TRUE
NULL

#' Search approximate matches with the Rust `sassy` crate.
rs_search <- function(pattern, text, k, alphabet, rc, alpha, all) .Call(wrap__rs_search, pattern, text, k, alphabet, rc, alpha, all)

# nolint end
